# E-commerce Customer & Campaign Analytics

## Phase 2

### Data Understanding

In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [8]:
customers = pd.read_csv("../data/raw/olist_customers_dataset.csv")

orders = pd.read_csv("../data/raw/olist_orders_dataset.csv")

order_items = pd.read_csv("../data/raw/olist_order_items_dataset.csv")

payments = pd.read_csv("../data/raw/olist_order_payments_dataset.csv")

products = pd.read_csv("../data/raw/olist_products_dataset.csv")

reviews = pd.read_csv("../data/raw/olist_order_reviews_dataset.csv")

sellers = pd.read_csv("../data/raw/olist_sellers_dataset.csv")

geolocation = pd.read_csv("../data/raw/olist_geolocation_dataset.csv")

translation = pd.read_csv("../data/raw/product_category_name_translation.csv")

In [9]:
datasets = {
    "customers": customers,
    "orders": orders,
    "order_items": order_items,
    "payments": payments,
    "products": products,
    "reviews": reviews,
    "sellers": sellers,
    "geolocation": geolocation,
    "translation": translation
}

for name, df in datasets.items():
    print("=" * 50)
    print(name.upper())
    print(df.shape)

==================================================
CUSTOMERS
(99441, 5)
==================================================
ORDERS
(99441, 8)
==================================================
ORDER_ITEMS
(112650, 7)
==================================================
PAYMENTS
(103886, 5)
==================================================
PRODUCTS
(32951, 9)
==================================================
REVIEWS
(99224, 7)
==================================================
SELLERS
(3095, 4)
==================================================
GEOLOCATION
(1000163, 5)
==================================================
TRANSLATION
(71, 2)

In [10]:
df.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 71 entries, 0 to 70
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   product_category_name          71 non-null     str
 1   product_category_name_english  71 non-null     str
dtypes: str(2)
memory usage: 1.2 KB

In [12]:
df.describe(include="all")

       product_category_name product_category_name_english
count                     71                            71
unique                    71                            71
top             beleza_saude                 health_beauty
freq                       1                             1

In [13]:
df.sample(5)

   product_category_name product_category_name_english
42           moveis_sala         furniture_living_room
2             automotivo                          auto
20                 audio                         audio
12             papelaria                    stationery
62       casa_conforto_2                home_comfort_2